[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pydantic~=1.9.0",
    "requests~=2.27.1",
    "backoff~=1.11.1",
    "email-validator~=1.1.3",
]
build-backend = "setuptools.build_meta"